#
#
#spring:
#  application:
#    name: ss-common
#    # 重写bean
#  main:
#    allow-bean-definition-overriding: true
#  datasource:
#    #   数据源基本配置
#    url: jdbc:mysql://localhost:3305/open_order_take_out?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    #   数据源其他配置
#    druid:
#      #     配置初始化大小、最小、最大线程数
#      initialSize: 5
#      minIdle: 5
#      #     CPU核数+1，也可以大些但不要超过20，数据库加锁时连接过多性能下降
#      maxActive: 20
#      #     最大等待时间，内网：800，外网：1200（三次握手1s）
#      maxWait: 60000
#      timeBetweenEvictionRunsMillis: 60000
#      #     配置一个连接在池中最大空间时间，单位是毫秒
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 1
#      testWhileIdle: true
#      #     设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
#      testOnBorrow: true
#      #     设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
#      testOnReturn: true
#      #     可以支持PSCache（提升写入、查询效率）
#      poolPreparedStatements: true
#
#      #     保持长连接
#      keepAlive: true
#      maxPoolPreparedStatementPerConnectionSize: 20
#      useGlobalDataSourceStat: true
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#
#dubbo:
#  # 元数据配置
#  metadata-report:
#    address: nacos://127.0.0.1:8848
#  protocol:
#    port: -1 # -1表示自增端口，从20280开始
#    name: dubbo
#  # 包扫描
#  scan:
#    base-packages: top.starshine.commons.dubbo
#  # 注册到nacos
#  registry:
#    address: nacos://127.0.0.1:8848
#
#
#
#
# 配置dubbo provider 和 consumer 的dubbofilter
# dubbofilter的文件路径
# resources/META-INF/dubbo/internal/com.alibaba.dubbo.rpc.Filter
# 缺少的话，ThreadLocal获取为null
dubbo:
  provider:
    filter: providerContextFilter
  consumer:
    filter: consumerContextFilter


starshine:

  thread:
    pool:
      maximum-pool-size: 50
      core-pool-size: 20
      keep-alive-time: 500
      work-queue-size: 10